<?php
$l['number'] 						= 'Invoice Number';
$l['date'] 							= 'Invoice Date';
$l['quote_date'] 				    = 'Quote date';
$l['due'] 							= 'Due date';
$l['to'] 							= 'Billing to';
$l['credit_note']					= 'Credit to';
$l['from'] 							= 'Our information';
$l['product'] 						= 'Product / Service';
$l['amount'] 						= 'Units';
$l['price'] 						= 'Total';
$l['discount'] 						= 'Discount';
$l['vat'] 							= 'Price';
$l['total'] 						= 'Total';
$l['page'] 							= 'Page';
$l['page_of'] 						= 'of';
?>